### ISSUE TITLE
Cannot use some solvers

### ISSUE THREAD

**Issue by DruvPai** [conda-forge/assimulo-feedstock#24]
Issue: Some solvers fail to import and required files are missing from the `assimulo/lib` folder. In particular, I get the following in a Python prompt:
```
>>> from assimulo.solvers import *
Could not find cannot import name 'radau5'
Could not find cannot import name 'dopri5'
Could not find cannot import name 'rodas'
Could not find cannot import name 'odassl'
Could not find ODEPACK functions.
Could not find RADAR5
Could not find GLIMDA.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/druvpai/anaconda3/envs/ECAR/lib/python3.6/site-packages/assimulo/solvers/radau5.py", line 30, in <module>
    from assimulo.lib import radau5
ImportError: cannot import name 'radau5'
```
No such issue occurs with `assimulo.problem`.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/druvpai/anaconda3/envs/ECAR:
#
# Name                    Version                   Build  Channel
assimulo                  3.0              py36h7eb728f_1    conda-forge
blas                      1.1                    openblas    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
libcxx                    4.0.1                hcfea43d_1
libcxxabi                 4.0.1                hcfea43d_1
libedit                   3.1.20170329         hb402a30_2
libffi                    3.2.1                h475c297_4
libgfortran               3.0.1                h93005f0_2
libopenblas               0.3.3                hdc02c5d_3
libpng                    1.6.36               ha92aebf_0    conda-forge
matplotlib                3.0.2                    py36_1    conda-forge
matplotlib-base           3.0.2            py36hb2d221d_1    conda-forge
metis                     5.1.0                hfc679d8_3    conda-forge
ncurses                   6.1                  h0a44026_1
nose                      1.3.7                 py36_1002    conda-forge
numpy                     1.15.4          py36_blas_openblashb06ca3d_0  [blas_openblas]  conda-forge
numpy-base                1.15.4           py36ha711998_0
openblas                  0.3.3                ha44fe06_1    conda-forge
openssl                   1.0.2p               h470a237_2    conda-forge
pip                       18.1                     py36_0
pyparsing                 2.3.0                      py_0    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
readline                  7.0                  h1de35cc_5
scipy                     1.2.0           py36_blas_openblashb06ca3d_200  [blas_openblas]  conda-forge
setuptools                40.6.3                   py36_0
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.26.0               ha441bb4_0
suitesparse               4.5.6           blas_openblash697e320_201  [blas_openblas]  conda-forge
sundials                  3.2.0           blas_openblash50a6636_0  [blas_openblas]  conda-forge
tbb                       2019.3               h2d50403_0    conda-forge
tk                        8.6.8                ha441bb4_0
tornado                   5.1.1            py36h470a237_0    conda-forge
wheel                     0.32.3                   py36_0
xz                        5.2.4                h1de35cc_4
zlib                      1.2.11               h1de35cc_3
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
active environment : ECAR
    active env location : /Users/druvpai/anaconda3/envs/ECAR
            shell level : 1
       user config file : /Users/druvpai/.condarc
 populated config files : /Users/druvpai/.condarc
          conda version : 4.5.12
    conda-build version : 3.10.5
         python version : 3.6.6.final.0
       base environment : /Users/druvpai/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/druvpai/anaconda3/pkgs
                          /Users/druvpai/.conda/pkgs
       envs directories : /Users/druvpai/anaconda3/envs
                          /Users/druvpai/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.6.6 Darwin/18.2.0 OSX/10.14.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by jschueller** [comment]
fixed in #25

**Comment by DruvPai** [comment]
Thanks! Works as intended now.

**Comment by marciobez** [comment]
Hello there,

I did not quite get what was done to fix the issue. Would someone be kind enough as to explain what to do?

Very much appreciated.
